function [Num,Den,P_rls,X_rls] = TFM_U6_IRLS(Input,Output,Num,Den,P_rls,X_rls)
% FUNCION QUE IMPLEMENTA EL MÉTODO DE MINIMOS CUADRADOS RECURSIVOS (RLS)
% PARAMETROS DE ENTRADA:
%   INPUT: ENTRADA AL SISTEMA EN EL INSTANTE ACTUAL
%   OUTPUT: SALIDA DEL SISTEMA EN EL INSTANTE ACTUAL
%   NUM: VECTOR QUE CONTIENE LOS COEFICIENTES ACTUALES DEL NUMERADOR DE LA FUNCION DE TRANSFERENCIA A IDENTIFICAR
%   DEN: VECTOR QUE CONTIENE LOS COEFICIENTES ACTUALES DEL DENOMINADOR DE LA FUNCION DE TRANSFERENCIA A IDENTIFICAR
%   P_RLS Y X_RLS: PARÁMETROS INTERNOS QUE SE DEBEN REUTILIZAR EN CADA LLAMADA. 
%                  LA PRIMERA VEZ SE PASARÁ UNA MATRIZ VACÍA [], EN POSTERIORES 
%                  LLAMADAS SE USARÁN LOS VALORES DEVUELTOS POR TFM_U6_RLS.

% SE AGREGA EL 1 INICIAL AL DENOMINADOR
Den = [1 Den];

% SI ES LA PRIMERA EJECUCION, SE INICIALIZAN LAS VARIABLES INTERNAS
if isempty(X_rls)
    order_N = length(Num);
    order_D = length(Den);
    % CREACION DE LA MATRIZ DE COVARIANZA INICIAL (GRANDE PARA UNA RAPIDA CONVERGENCIA)
    P_rls = diag(rand(1,order_N+order_D-1) * 1000);
    % INICIALIZACIÓN DEL VECTOR REGRESOR
    X_rls = rand(order_N+order_D-1,1) / 1000;
end

% CALCULO DEL SISTEMA IDENTIFICADO EN ESTA ITERACION USANDO RLS
[Num,Den,P_rls,X_rls] = TFM_U6_RLS(Input,Output,Num,Den,P_rls,X_rls);

% ELIMINAR EL 1 INICIAL DEL DENOMINADOR
Den = Den(2:end);

end
